### ISSUE TITLE
Bug: API always creates 4 images

### ISSUE THREAD

**Issue by ejkkan** [Leonardo-Interactive/leonardo-ts-sdk#40]
`num_images` seems to be ignored by the SDK. No mather the value it always generates four images.

**Comment by ejkkan** [comment]
Anyone from the Leonardo team who could acknowledge this?

**Comment by alexadrake** [comment]
Hey @ejkkan, can you provide an example of how you're using the SDK that is causing this to occur?

**Comment by ejkkan** [comment]
@anuraagnalluri 
I've created this example for most of the issues I've reported. [See here](https://github.com/ejkkan/leonardo-ai-template/tree/master) 
So please config it to make the setup relevant for each issue.
Notice that I'm using v1.28 specifically because of functionality being broken [as mentioned in](https://github.com/Leonardo-Interactive/leonardo-ts-sdk/issues/39)

**Comment by alexadrake** [comment]
Hi @ejkkan , I believe that this should have been resolved with the patch that resolved the other issues you submitted.

**Comment by ejkkan** [comment]
It is fixed indeed! Thanks!

**Comment by jessejamesrich** [comment]
Hey @alexadrake, I'm still seeing this exact behaviour in 2.2.0. Of note, at https://docs.leonardo.ai/reference/creategeneration this issue does not exist. 

`const generationResponse = await sdk.generation.createGeneration({
        modelId: '...',
        presetStyle: "ILLUSTRATION",
        num_images: 1,
        height: 1024,
        width: 1024,
        alchemy: true,
        photoReal: false,
        public: false,
        nsfw: false,
        elements: [{ akUUID: '...', weight: 1 }],
      },);`
